[workspace]
members = [
    "rust-connectors/common",
    "rust-connectors/sources/syslog",
    "rust-connectors/sources/test-connector",
    "rust-connectors/sources/mqtt",
    "rust-connectors/sources/http-json",
]
resolver = "2"
[patch.crates-io]
fluvio = { git = "https://github.com/simlay/fluvio", branch = "add-smartstream-to-producer"}
