[workspace]
members = [
    "rust-connectors/common",
    "rust-connectors/sources/syslog",
    "rust-connectors/sources/mqtt",
    "rust-connectors/sources/http",
    "rust-connectors/sources/postgres",
    "rust-connectors/models/fluvio-model-postgres",
    "rust-connectors/utils/mocks/http-json-mock/",
    "rust-connectors/utils/test-connector",
    "rust-connectors/utils/fluvio-smartstream-map/"
]
resolver = "2"
