version: v1
name: fluvio-postgres
type: postgres
topic: postgres
parameters:
  url: postgres://postgres:mysecretpassword@postgres-leader-service:5432?replication=database
  publication: fluvio
  slot: fluvio
  topic: postgres