[[source]]
name = "flv_sc.log"
type = "syslog"
filter_prefix = "fluvio"
topic = "flv-sc-syslog"
create_topic = true
input_file = "./test-data/flv_sc.log"

[[source]]
name = "flv-spu-5001-syslog"
type = "syslog"
filter_prefix = "fluvio"
topic = "flv-spu-5001-syslog"
create_topic = true
input_file = "/tmp/spu_log_5001.log"
